### ISSUE TITLE
Inputs and Variables for the Model

### ISSUE THREAD

**Issue by sulays** [moja-global/GSoC.FLINT.Module.Agricultural_Soil_Model#1]
## Variables
Excel tables should be created for these variables to use them in the code when needed.
#### Emission Factors:
 - EF<sub>1</sub> - is the amount of N2O emitted from the various synthetic and organic N applications to soils, including crop residue and mineralization of soil organic carbon in mineral soils due to land-use change or management. It is further segregated into wet and dry climates. Given in Table 11.1
 - EF<sub>1FR</sub> - is for flooded rice fields. Further segregated into continuous flooding. Also given in Table 11.1
 - EF<sub>2</sub> - is the amount of N2O emitted from an area of drained/managed organic soils. Segregated based on land use and climate/vegetation zone. Given in 2013 Supplement to the 2006 IPCC Guidelines for National Greenhouse Gas Inventories: Wetlands, Chapter 2, Table 2.5.
 - EF<sub>3PRP</sub> - estimates the amount of N2O emitted from urine and dung N deposited by grazing animals on pasture, range and paddock. Classified into 2 categories - 'cattle, poultry, pig' and 'sheep and other animals'. Given in Table 11.1

 
## Inputs
 - F<sub>SN</sub> - refers to the annual amount of synthetic N fertiliser applied to soils. It is estimated from the total amount of synthetic fertiliser consumed annually. If country-specific data are not available, data can be used from the IFA (http://www.fertilizer.org/ifa/statistics.asp) on total fertiliser use by type and by crop, or from the FAO (http://fao.org/faostat/) on synthetic fertiliser consumption.
 - F<sub>ON</sub> - refers to the amount of organic N inputs applied to soils other than by grazing animals. It is calculated using the following inputs:
	 - F<sub>AM</sub> - amount of animal manure N applied to soils
	 - F<sub>SEW</sub> - amount of total sewage N applied to soils
	 - F<sub>COMP</sub> - amount of total compost N applied to soils
	 - F<sub>OOA</sub> - amount of other organic amendments used as fertiliser
- F<sub>AM</sub> - is determined by adjusting the amount of manure N available. It needs the following quantities:
	- N<sub>MMSAvb</sub> - amount of managed manure N available for soil application, feed, fuel or construction
	- FRAC<sub>Feed</sub> - fraction of managed manure used for feed
	- FRAC<sub>Fuel</sub> - fraction of managed manure used for fuel
	- FRAC<sub>CNST</sub> - fraction of managed manure used for construction
if the fractions are not available then F<sub>AM</sub> = N<sub>MMSAvb</sub>
- F<sub>PRP</sub> - refers to the annual amount of N deposited on pasture, range and paddock soils by grazing animals. It is calculated using:
	- N<sub>(T)</sub> -  number of head of livestock species/category T in the country
	- Nex<sub>(T)</sub> -  average N excretion per head of species/category T in the country
	- MS<sub>(T,PRP)</sub> - fraction of total annual N excretion for each livestock species/category T that is deposited on pasture, range and paddock
- F<sub>SOM</sub> - the net annual amount of N mineralised in mineral soils as a result of loss of soil carbon through change in land use or management. This is calculated by the following quantities:
	- ΔC<sub>Mineral,LU</sub> - average annual loss of soil carbon for each land-use type (LU). Using the Tier 1 approach, the value for ΔC<sub>Mineral,LU</sub> will have a single value for all land-uses and management systems. Using Tier 2, the value for ΔC<sub>Mineral,LU</sub> will be disaggregated by individual land-use and/or management systems. Calculation for this is shown in https://www.ipcc-nggip.iges.or.jp/public/2019rf/pdf/4_Volume4/Vol4_Ch10_%20MCF_Calculation-Spreadsheet.xlsx
	- R - C:N ratio of the soil organic matter.  A default value of 15 for the C:N ratio (R) may be used for situations involving land-use change from ForestLandor Grassland to Cropland, in the absence of more specific data for the area. A default value of 10 may be used for situations involving management changes on Cropland Remaining Cropland.
- F<sub>OS</sub> - refers to the total annual area (ha) of drained/managed organic soils. 
- F<sub>CR</sub> - refers to the amount of N in crop residues (above-ground and below-ground), including N-fixing crops, returned to soils.  It is calculated using the following quantities:
	- AGR<sub>(T)</sub> - total amount of above-ground crop residue for crop T
	- N<sub>AG(T)</sub> -  N content of above-ground residues for crop T. (Table 11.1a)
	- Frac<sub>Remove(T)</sub> - fraction of above-ground residues of crop T removed annually for purposes such as feed, bedding and construction, dimensionless. If data not available then 0.
	- Frac<sub>Burnt(T)</sub> - fraction of harvested area of crop T burnt
	- C<sub>f</sub> - Combustion factor (Chapter 2, Table 2.6)
	- BGR<sub>(T)</sub> - total amount of belowground crop residue for crop T
	- N<sub>BG(T)</sub> - N content of below-ground residues for crop T
	- AG<sub>DM(T)</sub> - Above-ground residue dry matter for crop T
	Calculated using Crop<sub>(T)</sub>: harvested dry matter yield for crop T and R<sub>AG(T)</sub> : ratio of above-ground residue dry matter to harvested yield for crop T.
	Crop<sub>(T)</sub> is calculated by DRY: dry matter fraction of harvested crop T and Yield_Fresh<sub>(T)</sub>
	- Area<sub>(T)</sub> - total area harvested of crop T
	- Frac<sub>Renew(T)</sub> - fraction of total area under crop T that is renewed annually. For countries where pastures are renewed on average every X years, Frac~Renew(T)~= 1/X. For annual crops Frac<sub>Renew(T)</sub>= 1
	- RS<sub>(T)</sub> - ratio of below-ground root biomass to above-ground shoot biomass for crop T
N<sub>AG(T)</sub>, N<sub>BG(T)</sub>, R<sub>AG(T)</sub>, RS<sub>(T)</sub>, DRY are available for different crops in Table 11.1a

**Comment by RobboW** [comment]
Thanks Sulay,

Just a few quick points on the inputs that may help. The calculations in the IPCC documents are all done for an annual number. However, in the FLINT we will often run at monthly time steps and we often apply 'events' such as applying fertiliser on a day (with the months then being subdivided). So there are effectively 2 type of activities:

1. application on a day (such as fertiliser application) that has an application date
2. application over a period of time (for example, irrigation) that has a start and end date

There are also two processes for how emissions occur
- all emissions occur on the day of the event (or each day over a period under method 2)
- emissions start on the day then continue for a period of time (for example. when you apply N fertiliser the emissions will occur over a few weeks.

So, when we consider how to do the calculation of the EFs we need to consider these issues and how they interact. Can discuss more if that helps

**Comment by sulays** [comment]
I have a few doubts:

- For fertilizer application, the quantity will be added to F<sub>SN</sub> but for an event like irrigation what input quantity will be changed?

- Also, how to determine the period of time during which the emission occurs? The IPCC documents have only documented how to calculate the total emissions at the end of the year.

- If possible, could we discuss what all activities could take place and how they affect the model inputs?

**Comment by RobboW** [comment]
Thanks Sulay,

Yes, the issue is the IPCC focused only on GHG inventory, we are interested in this and getting good farm level estimates as well. 

- Yes, for fertiliser application it will typically occur on a day: but it may occur several times in a year and we want to be able to input the day it was applied and how much. We can then add up to years through the process. And don;t worry about the irrigation example for the time being
- There are a number of studies on the pattern of emissions from fertiliser: the emissions do not all occur on a day. So, I would suggest two options here 1) simple where we assume all the emissions occur on the day of the fertiliser application and 2) where we spread it out over x days from the day of application. We don't need to get any more complicated than that for the time being.
- Yes, happy to discuss all of these!

I think the best way to start may be to build this in a google sheet or the like that we can share and comment on. Would you be happy to start with that?

Thanks
Rob

**Comment by sulays** [comment]
Thanks Rob,

Yes, I would be happy to start building this in a google sheet. I will share the document on Slack.
